### ISSUE TITLE
Generate Script > Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by TheDevCactus** [ThePrimeagen/kata-machine#6]
## Description
While generating your first day's katas, the generate script will run into an error in the following code block due to there being no found "day" directories, and then trying to access the 0'th index of the array containing these "day" directories.

```js
// scripts/generate

day = +fs.readdirSync(src_path).
        filter(i => i.includes("day")).
        sort((a, b) => {
            return +b.substring(3) - a.substring(3);
        })[0].substring(3) + 1;
```

## Proposed Solution
Wrote this up right quick. You can ditch the whole try catch block now. 
```js
// scripts/generate

const previousDayDirs = fs
    .readdirSync(src_path)
    .filter(dirName => dirName.includes("day"));

const day = previousDayDirs.length
    ? previousDayDirs.sort((a, b) => (
        +b.substring(3) - a.substring(3)
    ))[0].substring(3) + 1
    : 1;
```

**Comment by ThePrimeagen** [comment]
i believe i may have fixed this :)

**Comment by ThePrimeagen** [comment]
actually.. i haven't
but it does still work when you generate :)

**Comment by ThePrimeagen** [comment]
i believe i fixed this ;)

**Comment by jmakwana01** [comment]
i am still unable to generate
![image](https://user-images.githubusercontent.com/87368354/190305591-d6918c31-7d37-47d5-b978-ef757acb2e8f.png)

**Comment by osigie** [comment]
I am unable to generate too, have you been able to resolve it jmakwana01?

**Comment by KarthikRaju391** [comment]
I haven't been able to run the generate script too. I believe it relates to how 'paths' are read differently in Linux and Windows. But I am not sure...

**Comment by osigie** [comment]
oh I think so

**Comment by jmakwana01** [comment]
yes not able to generate on a windows machine , do let me know if some solution comes up looking forward to follow the course
@ThePrimeagen @osigie

**Comment by osigie** [comment]
Okay sure

**Comment by osigie** [comment]
I think windows do not support  #!/usr/bin/env node shebang line. so I removed the line and ran the script with node. Run node scripts/generate in your terminal

**Comment by KarthikRaju391** [comment]
Yes, that worked! Thank you @osigie!
